### ISSUE TITLE
A native way to set a game objects rotation in conventional way.

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#123]
self.gameobj.rotation = -math.degrees(self.desired_direction.angle + math.pi / 2)

right now this is what we need to do to convert to the proper rotation for our sprites.

I think that:
a) we should get a function that does this, what's a name for something like this?
b) maybe our rotation should just be in radians anyways (counterclockwise starting from right like unit circle).

**Comment by tinmarr** [comment]
Will be fixed by #127
