### ISSUE TITLE
Useless game object creation with UI

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#141]
All UI components need a GameObject due to our GameObject based style. However, in reality, it is uncommon that you will be adding multiple UI components to your GameObject / there is no reason first to make a GameObject and then add one UI component to it.

Proposing a function: UI.getGameObj(). Where you pass in the defaults for the GameObject and the UI component at once, and it passes back the GO, Component.

Still not thought out completely.

**Comment by tinmarr** [comment]
Basically, create a component and call it's getGO()
