### ISSUE TITLE
Radio event naming needs explicit documentation.

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#160]
**ISSUE**:
We have naming that is not easily found. 
A) this naming for radio events is not mentioned anywhere in the documentation. 
B) Events in SDL is done with variable names equal to integers because it is faster. We might want to shift to use this.

Regardless we need documentation.

![image](https://user-images.githubusercontent.com/52299477/172541138-6df2b647-00b9-4577-b7dc-fad39ffee5c4.png)

Ex: In no place is it mentioned that listener has a KEYUP event broadcasted.

**Comment by tinmarr** [comment]
@mrElnekave I agree in regards to the number thing. I don't if it's faster in python but if it is then we should consider it.

Does [this](https://rubato.app/latest/events/) not address your other point?

**Comment by tsedan** [comment]
Looks like this is done? Closing
