### ISSUE TITLE
custom component singular bug

### ISSUE THREAD

**Issue by mvaganov** [rubatopy/rubato#164]
*Make sure that you read the documentation for said item, and are using it correctly. Thank you.*
While creating a custom component, the "singular bug" was hit

**To Reproduce**
Steps to reproduce the behaviour:
```Py
import rubato as rb

rb.init()

main_scene = rb.Scene()

player = rb.GameObject("red dot", rb.Display.center)

class Player (rb.Component):
    def __init__(self):
        self.color = rb.Color.red

player_data = Player()
player.add(player_data)

def scene_update():
    print("hi")

def scene_draw():
    rb.Draw.point(player.pos, player.get(Player).color)

main_scene.update = scene_update
main_scene.draw = scene_draw

rb.begin()
```

**Expected behaviour**
that should crash it

**Screenshots**
![image](https://user-images.githubusercontent.com/2280946/173173220-2e3f1b54-50d5-4b1a-bc8e-ba7bb037dcb0.png)

**Additional context**
Found with Yamm

**Comment by tinmarr** [comment]
This is an issue caused by lack of documentation surrounding how to make custom components. Calling the `super.__init__()` will fix this problem and is the intended way of creating components. Making lots of tutorials is our next priority.
