### ISSUE TITLE
Add class-specific demos in the full api documentation

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#185]
**Is your feature request related to a problem? Please describe.**
We need the demos accessible to the public

**Describe the solution you'd like**
Slowly roll this out.

**Utils Folder**
- [ ] Color
- [ ] Display
- [ ] Font
- [ ] Noise
- [ ] Draw
- [ ] Debug
- [ ] Radio
- [ ] Input
- [ ] Math
- [ ] Sound
- [ ] Time
- [ ] Vector

**Classes Folder**
- [ ] Camera
- [ ] Game Object
- [ ] Group
- [ ] Scene Manager
- [ ] Scene

**Components Folder**
- [ ] Component 
- [ ] Animation
- [ ] Button
- [ ] Engine
- [ ] Hitbox
- [ ] Image
- [ ] Raster
- [ ] Rigidbody
- [ ] Spritesheet
- [ ] Text

**Comment by tinmarr** [comment]
Platformer demo will cover more things and the remain stuff will be in demos. I'll also add links to the demo folder in the website.
