### ISSUE TITLE
Check if rotation is still bad

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#186]
![image](https://user-images.githubusercontent.com/52299477/173459171-27c9b0bb-b055-4c93-9cfa-b2f2d4694241.png)

This was noticed, investigate further.

**Comment by mrElnekave** [comment]
Update: this might be an sdl2gfx issue?
![image](https://user-images.githubusercontent.com/52299477/173459577-ee896669-1dc7-44c6-afd5-6a5d03d1b018.png)

**Comment by mrElnekave** [comment]
counter-clockwise rotation from north

**Comment by tinmarr** [comment]
Closed by #195
