### ISSUE TITLE
BUG: Image jitter and rounding

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#241]
## Describe the bug
When the image, or rectangle that will be drawn is of an odd size the image will jitter. 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to [repository](https://github.com/mrElnekave/Rubato-Examples)
2. Run multi_scene.py and run into the wall.
3. The image moves from pixel to pixel and will jitter.

## Expected behaviour
Remove jittering, this can be done by adding pixels or rounding or some other. We also experience an offset of an image and rectangle defined to be the same size. As well as image asynchronies.

![image](https://user-images.githubusercontent.com/52299477/177690806-3e59bf85-68b4-42f7-abb6-1433899f0834.png)
![image](https://user-images.githubusercontent.com/52299477/177690833-47a4122a-4866-4190-9332-4f92f5b05464.png)
![image](https://user-images.githubusercontent.com/52299477/177690851-a4df5c15-39cf-407b-9828-6ed6838c8eab.png)

## Screenshots
kill me now, it fixes when u screenshot.

**Comment by tinmarr** [comment]
Not actually an issue. Just bad code 😉

**Comment by mrElnekave** [comment]
Nope it did have issues lol.

**Comment by tsedan** [comment]
Unless @mrElnekave wants to address this issue himself, closing and marking as wontfix because the bug is not clearly defined to where I can tell what is going wrong.
