### ISSUE TITLE
FEATURE: reorganize internal file structure

### ISSUE THREAD

**Issue by tsedan** [rubatopy/rubato#255]
Many of the folders in our current Rubato file hierarchy have tens of files in them. We want to make it sleeker by grouping files into more intuitive directories. The utils folder especially needs a lot of love.

@tinmarr can we also move the test folder out of the rubato directory (and into the root repo)? I don't want it to bundle into releases with pypi.

**Comment by tinmarr** [comment]
Yes we can I will take care of it.
