### ISSUE TITLE
FEATURE: Clone

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#269]
## Is your feature request related to a problem? Please describe.
Only some of the components in our library have a clone method, all of them should.

## Describe the solution you'd like
More of da cologne.

## Describe alternatives you've considered
Less cologne is less fun.

**Comment by tsedan** [comment]
As a part of this issue @mrElnekave please test that existing clone methods function properly because I am not sure that they do.

**Comment by tinmarr** [comment]
Turns out that this was done a while ago
