### ISSUE TITLE
FEATURE: Remove SDL_GFX Dependency

### ISSUE THREAD

**Issue by tinmarr** [rubatopy/rubato#301]
This would allow us to use the official versions of SDL for mac and not the scuffed Homebrew version. Staying with Homebrew would make it harder to update SDL in the future.

I think we only use SDL_GFX for image scaling and rotation, but this can be done directly at the render step.

Once this is done, I would also like to remove the Homebrew SDL from our library and use the official releases.

Needs #140 or #311

**Comment by tsedan** [comment]
Note we also use SDLgfx for shape drawing to the renderer, but rasters should implement this functionality in a way that does not require SDLgfx so that we can phase it out of use.

**Comment by tinmarr** [comment]
Pretty much done. Remaining sdl gfx is in `draw.py` and will be removed by #352
