### ISSUE TITLE
BUG: Image.get_rect not working

### ISSUE THREAD

**Issue by Qwerty32768** [rubatopy/rubato#345]
*Make sure that you read the documentation for said item, and are using it correctly. Thank you.*

## Describe the bug
*A clear and concise description of what the bug is.*
When Image.get_rect() is used on a scaled image, it returns a rect for the base image and not the scaled one. 

## To Reproduce
Steps to reproduce the behaviour:
Load an image, scale it, and get the rect. The rect should have the size of the base image. 

## Expected behaviour
*A clear and concise description of what you expected to happen.*

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Additional context
*Add any other context about the problem here.*

**Comment by tinmarr** [comment]
Potentially fixed by the Hitbox refactoring. Needs double checkinging
