### ISSUE TITLE
Font and text are too interlinked

### ISSUE THREAD

**Issue by tinmarr** [rubatopy/rubato#409]
for example, changing the text.font_size also changes the font.size which changes all the other text's font sizes as well.

A temp fix is to clone the font every time but that's expensive and defeats the point of font.

**Comment by tinmarr** [comment]
from tomer: I think the proper solution to that is to just remove the methods in text that change font stuff under the hood. That way it’s way more obvious to devs that not copying the font will cause issues. Itll also make our code much cleaner

**Comment by mrElnekave** [comment]
Multiple fonts must clone
