### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#41]
Rotate images around their centre nicely using this.
(https://stackoverflow.com/questions/4183208/how-do-i-rotate-an-image-around-its-center-using-pygame)

**Comment by tinmarr** [comment]
Image rotation is not supported in SDL (for real time). If we want this functionality we should use opengl rendering instead. (This will require large rewrites)

**Comment by tinmarr** [comment]
HAHAH just kidding

**Comment by tinmarr** [comment]
Rotations work now with SDL
