### ISSUE TITLE
modifier key is considered pressed when it isnt

### ISSUE THREAD

**Issue by tsedan** [rubatopy/rubato#65]
how to replicate:
run the ball pit, and resize the window by holding shift. release shift BEFORE releasing the mouse cursor to end the resize operation. Now if you press "a" the secret combo will print even when shift is not pressed.

could be a mac only issue, could also be an SDL issue and therefore unfixable, not sure so assigning to martin.

**Comment by tinmarr** [comment]
Can't replicate with the given instructions... could be just a mac problem?

**Comment by tinmarr** [comment]
Mac only problem.
