### ISSUE TITLE
Add perlin noise function

### ISSUE THREAD

**Issue by tinmarr** [rubatopy/rubato#68]
In math. Like unity

**Comment by mrElnekave** [comment]
Perlin noise integrated in commit: 47a6b1028bb5e23b90e1ac49ba0ae82584cfcf6f

**Comment by tinmarr** [comment]
Add a blurb in the documentation about how to do

**Comment by mrElnekave** [comment]
Perlin noise removed and now should use "import opensimplex"
This issue now revolves around creating the documentation for this.
