### ISSUE TITLE
create helper function allowing to import an entire folder of spritesheets

### ISSUE THREAD

**Issue by tsedan** [rubatopy/rubato#72]
Basically create a function that takes in a directory with spritesheet images, and import them all, adding them to an animation component automatically such that each filename (with extension removed) becomes the name for that respective animationstate.
i.e.:
I have a folder with idle.png and run.png, each of which is a spritesheet in which the individual sprites are the same size.
I run "import_from_folder(folder_dir)" and it imports all of the spritesheets into an animation object with the names "idle" and "run".

**Comment by mrElnekave** [comment]
Done on this commit: e56ddc0623ec04aeaedf94991f71a7f92cc99da3
