### ISSUE TITLE
Create functions wrappers for renderer in Display

### ISSUE THREAD

**Issue by mrElnekave** [rubatopy/rubato#74]
Create wrapper for all functions [here](https://pysdl2.readthedocs.io/en/0.9.11/modules/ext/renderer.html?highlight=Renderer#sdl2.ext.renderer.Renderer.draw_point) that we think a user might need without looking into SDL documentation.

DrawPoint
DrawLine
etc.

**Comment by mrElnekave** [comment]
place wrapper for renderer in Display
place wrapper for SDL_Surface in Image

**Comment by tinmarr** [comment]
We need to write a wrapper or explain how to use sdlgfx
